# Generated by Django 5.1.2 on 2025-02-24 23:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('rif', models.CharField(default='J-', max_length=12)),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('telefono_1', models.CharField(default='default_value', max_length=15)),
                ('telefono_2', models.CharField(default='default_value', max_length=15)),
                ('fecha_contrato', models.DateField(auto_now=True)),
                ('num_empleados', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Contacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cargo', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('telephone', models.CharField(default='default_value', max_length=15)),
                ('cellphone', models.CharField(default='default_value', max_length=15)),
                ('extension', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
