# Generated by Django 5.1.2 on 2025-02-25 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='rif',
            field=models.CharField(default='J-', max_length=12, unique=True),
        ),
    ]
