# Generated by Django 5.1 on 2025-03-31 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='krp_partners',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tin', models.CharField(default='J-', max_length=12, unique=True)),
                ('partner_type', models.CharField(max_length=24)),
                ('is_tax_exempt', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('economy_sector', models.CharField(max_length=24)),
                ('website', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('contract_d', models.DateField(auto_now=True)),
                ('empl_size', models.IntegerField(default=0)),
                ('phone1', models.CharField(default='default_value', max_length=15)),
                ('phone2', models.CharField(default='default_value', max_length=15)),
                ('pub_note', models.CharField(max_length=255)),
                ('pri_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='client_id',
        ),
        migrations.CreateModel(
            name='krp_partner_contacts',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=17)),
                ('middlename', models.CharField(max_length=15)),
                ('lastname1', models.CharField(max_length=17)),
                ('lastname2', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=64)),
                ('phone', models.CharField(default='default_value', max_length=15)),
                ('phone_ext', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('in_invoice', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='Cliente.krp_partners')),
            ],
        ),
    ]
