# Generated by Django 5.1.2 on 2025-02-25 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_alter_cliente_rif'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacto',
            old_name='client_id',
            new_name='cliente',
        ),
    ]
