# Generated by Django 5.1 on 2025-03-31 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_krp_partners_remove_contacto_client_id_and_more'),
        ('facturas', '0002_krp_invoices_krp_invoice_transactions_delete_factura'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Contacto',
        ),
    ]
