# Generated by Django 5.1 on 2025-04-02 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0003_delete_cliente_delete_contacto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartnerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=24)),
                ('address_lines', models.CharField(blank=True, max_length=120, null=True)),
                ('ref_address', models.CharField(blank=True, max_length=64, null=True)),
                ('country_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state_id', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('municipality', models.CharField(blank=True, max_length=64, null=True)),
                ('parish', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='Cliente.krp_partners')),
            ],
        ),
    ]
