# Generated by Django 5.1 on 2025-04-02 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0004_partneraddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PartnerAddress',
            new_name='krp_partner_address',
        ),
    ]
