# Generated by Django 5.1.2 on 2024-10-31 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.RenameField(
            model_name='factura',
            old_name='total',
            new_name='importe',
        ),
        migrations.AddField(
            model_name='factura',
            name='domicilio_fiscal',
            field=models.TextField(default='Sin domicilio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='forma_pago',
            field=models.CharField(default='default_value', max_length=50),
        ),
        migrations.AddField(
            model_name='factura',
            name='iva',
            field=models.IntegerField(choices=[(8, '8%'), (12, '12%'), (16, '16%')], default=16),
        ),
        migrations.AddField(
            model_name='factura',
            name='numero_factura',
            field=models.CharField(default='default_value', max_length=20, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='rif',
            field=models.CharField(default='default_value', max_length=12, unique=True),
        ),
        migrations.AddField(
            model_name='factura',
            name='telefono',
            field=models.CharField(default='default_value', max_length=15),
        ),
        migrations.AddField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='facturas.cliente'),
        ),
    ]
