# Generated by Django 5.1.2 on 2024-11-01 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0001_initial'),
        ('facturas', '0003_alter_factura_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente'),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
    ]
