# Generated by Django 5.1.2 on 2024-11-08 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0005_remove_factura_usuario_alter_factura_rif'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='forma_pago',
            field=models.TextField(),
        ),
    ]
