# Generated by Django 5.1.2 on 2025-02-24 23:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Cliente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=20, unique=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('rif', models.CharField(default='J-', max_length=12, unique=True)),
                ('domicilio_fiscal', models.TextField(default='Sin domicilio')),
                ('telefono', models.CharField(default='default_value', max_length=15)),
                ('descripcion', models.TextField()),
                ('forma_pago', models.TextField()),
                ('importe', models.DecimalField(decimal_places=2, max_digits=10)),
                ('iva', models.IntegerField(choices=[(8, '8%'), (12, '12%'), (16, '16%')], default=16)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.cliente')),
            ],
        ),
    ]
