# Generated by Django 5.1 on 2025-03-31 23:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Cliente', '0002_krp_partners_remove_contacto_client_id_and_more'),
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='krp_invoices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_n', models.CharField(max_length=20, unique=True)),
                ('invoice_d', models.DateTimeField(auto_now_add=True)),
                ('invoice_c', models.CharField(max_length=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_id', models.CharField(blank=True, max_length=4, null=True)),
                ('pub_note', models.CharField(blank=True, max_length=255, null=True)),
                ('pri_note', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Cliente.krp_partners')),
            ],
        ),
        migrations.CreateModel(
            name='krp_invoice_transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency_id', models.CharField(max_length=4)),
                ('curr_rate', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.krp_invoices')),
            ],
        ),
        migrations.DeleteModel(
            name='Factura',
        ),
    ]
