# Generated by Django 5.2 on 2025-04-11 19:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturas',
            name='invoice_d',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
