# Generated by Django 5.2 on 2025-05-01 03:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0003_alter_facturastransactions_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturastransactions',
            name='invoice_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='facturas.facturas'),
        ),
    ]
