# Generated by Django 5.1 on 2025-04-08 19:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('tin', models.CharField(default='J-', max_length=12, unique=True)),
                ('partner_type', models.CharField(max_length=24)),
                ('is_tax_exempt', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('economy_sector', models.CharField(max_length=24)),
                ('website', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=254)),
                ('contract_d', models.DateField(auto_now=True)),
                ('empl_size', models.IntegerField(default=0)),
                ('phone1', models.CharField(default='default_value', max_length=15)),
                ('phone2', models.CharField(default='default_value', max_length=15)),
                ('pub_note', models.CharField(max_length=255)),
                ('pri_note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('instance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('shortening', models.CharField(max_length=32)),
                ('lic_key', models.CharField(max_length=20)),
                ('tin', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=4)),
                ('nationality', models.CharField(blank=True, max_length=24, null=True)),
                ('natural_code', models.CharField(blank=True, max_length=3, null=True)),
                ('foreign_code', models.CharField(blank=True, max_length=3, null=True)),
                ('email_cfg_file', models.CharField(blank=True, max_length=64, null=True)),
                ('gen_employee_n', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('len_employee_n', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('lookat_job_sal', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('start_fy', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('audit_user', models.CharField(blank=True, max_length=64, null=True)),
                ('audit_dte', models.DateField(blank=True, null=True)),
                ('audit_track', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('kinder_age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('kinder_minwage', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('kinder_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kinder_payitem_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('lookat_dep_job', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('lookat_job_quota', models.CharField(default='na', max_length=24)),
                ('filename_logo', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'Compañia',
            },
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('company_id', models.CharField(max_length=24)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_qty', models.PositiveIntegerField()),
                ('currency_id', models.CharField(max_length=4)),
                ('is_tax_exempt', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('note', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Dominio o nombre de información.', max_length=32)),
                ('item_value', models.CharField(help_text='Identificador elemento o valor.', max_length=24)),
                ('group_value', models.CharField(blank=True, help_text='Grupo del valor asociado.', max_length=24, null=True)),
                ('meaning', models.CharField(blank=True, help_text='Nombre o descripción de elemento.', max_length=64, null=True)),
                ('mean_label', models.CharField(blank=True, help_text='Etiqueta o descripción del elemento.', max_length=64, null=True)),
                ('order_val', models.DecimalField(blank=True, decimal_places=3, help_text='Valor de orden numérico.', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'db_table': 'Referencias',
            },
        ),
        migrations.CreateModel(
            name='ClienteDireccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_type', models.CharField(max_length=24)),
                ('address_lines', models.CharField(blank=True, max_length=120, null=True)),
                ('ref_address', models.CharField(blank=True, max_length=64, null=True)),
                ('country_id', models.CharField(blank=True, max_length=64, null=True)),
                ('state_id', models.CharField(blank=True, max_length=64, null=True)),
                ('city', models.CharField(blank=True, max_length=64, null=True)),
                ('municipality', models.CharField(blank=True, max_length=64, null=True)),
                ('parish', models.CharField(blank=True, max_length=64, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='facturas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='ClienteContactos',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=17)),
                ('middlename', models.CharField(max_length=15)),
                ('lastname1', models.CharField(max_length=17)),
                ('lastname2', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=64)),
                ('phone', models.CharField(default='default_value', max_length=15)),
                ('phone_ext', models.CharField(blank=True, max_length=6, null=True)),
                ('mobile', models.CharField(blank=True, max_length=10, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('in_invoice', models.IntegerField(choices=[(0, 'False'), (1, 'True')], default=0)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contactos', to='facturas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='Facturas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_n', models.CharField(max_length=20, unique=True)),
                ('invoice_d', models.DateTimeField(auto_now_add=True)),
                ('invoice_c', models.CharField(max_length=7)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('currency_id', models.CharField(blank=True, max_length=4, null=True)),
                ('pub_note', models.CharField(blank=True, max_length=255, null=True)),
                ('pri_note', models.CharField(blank=True, max_length=255, null=True)),
                ('partner_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.clientes')),
            ],
        ),
        migrations.CreateModel(
            name='FacturasTransactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.BigIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=15)),
                ('qty', models.PositiveIntegerField()),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('vat_rate', models.DecimalField(decimal_places=2, max_digits=5)),
                ('currency_id', models.CharField(max_length=4)),
                ('curr_rate', models.DecimalField(decimal_places=5, default=0, max_digits=9)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
                ('invoice_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.facturas')),
            ],
        ),
    ]
