# Generated by Django 5.2 on 2025-04-12 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_alter_facturas_invoice_d'),
    ]

    operations = [
        migrations.AlterField(
            model_name='facturastransactions',
            name='product_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facturas.productos'),
        ),
    ]
