# Generated by Django 5.1 on 2025-04-05 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facturas', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compañia',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('instance', models.DecimalField(decimal_places=0, max_digits=10)),
                ('name', models.CharField(max_length=64)),
                ('shortening', models.CharField(max_length=32)),
                ('lic_key', models.CharField(max_length=20)),
                ('tin', models.CharField(max_length=20)),
                ('country_id', models.CharField(max_length=4)),
                ('nationality', models.CharField(blank=True, max_length=24, null=True)),
                ('natural_code', models.CharField(blank=True, max_length=3, null=True)),
                ('foreign_code', models.CharField(blank=True, max_length=3, null=True)),
                ('email_cfg_file', models.CharField(blank=True, max_length=64, null=True)),
                ('gen_employee_n', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('len_employee_n', models.DecimalField(decimal_places=0, default=0, max_digits=2)),
                ('lookat_job_sal', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('start_fy', models.DecimalField(decimal_places=0, default=1, max_digits=2)),
                ('audit_user', models.CharField(blank=True, max_length=64, null=True)),
                ('audit_dte', models.DateField(blank=True, null=True)),
                ('audit_track', models.DecimalField(decimal_places=0, default=0, max_digits=10)),
                ('kinder_age', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('kinder_minwage', models.DecimalField(blank=True, decimal_places=0, max_digits=2, null=True)),
                ('kinder_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('kinder_payitem_id', models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True)),
                ('lookat_dep_job', models.DecimalField(decimal_places=0, default=0, max_digits=1)),
                ('lookat_job_quota', models.CharField(default='na', max_length=24)),
                ('filename_logo', models.CharField(blank=True, max_length=128, null=True)),
            ],
            options={
                'db_table': 'Compañia',
            },
        ),
        migrations.CreateModel(
            name='Referencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain_name', models.CharField(help_text='Dominio o nombre de información.', max_length=32)),
                ('item_value', models.CharField(help_text='Identificador elemento o valor.', max_length=24)),
                ('group_value', models.CharField(blank=True, help_text='Grupo del valor asociado.', max_length=24, null=True)),
                ('meaning', models.CharField(blank=True, help_text='Nombre o descripción de elemento.', max_length=64, null=True)),
                ('mean_label', models.CharField(blank=True, help_text='Etiqueta o descripción del elemento.', max_length=64, null=True)),
                ('order_val', models.DecimalField(blank=True, decimal_places=3, help_text='Valor de orden numérico.', max_digits=7, null=True)),
            ],
            options={
                'verbose_name': 'Referencia',
                'verbose_name_plural': 'Referencias',
                'db_table': 'Referencias',
            },
        ),
    ]
